// Auto-generated by scripts/generate-repl-types.ts — do not edit manually.
// Provides slim type declarations for the Prisma REPL Monaco editor.

declare const prisma: DB;
declare function randomUUID(): string;

interface Album {
  albumId: number;
  title: string;
  artistId: number;
}

interface Artist {
  artistId: number;
  name: string | null;
}

interface Customer {
  customerId: number;
  firstName: string;
  lastName: string;
  company: string | null;
  address: string | null;
  city: string | null;
  state: string | null;
  country: string | null;
  postalCode: string | null;
  phone: string | null;
  fax: string | null;
  email: string;
  supportRepId: number | null;
}

interface Employee {
  employeeId: number;
  lastName: string;
  firstName: string;
  title: string | null;
  reportsTo: number | null;
  birthDate: string | null;
  hireDate: string | null;
  address: string | null;
  city: string | null;
  state: string | null;
  country: string | null;
  postalCode: string | null;
  phone: string | null;
  fax: string | null;
  email: string | null;
}

interface Genre {
  genreId: number;
  name: string | null;
}

interface Invoice {
  invoiceId: number;
  customerId: number;
  invoiceDate: string;
  billingAddress: string | null;
  billingCity: string | null;
  billingState: string | null;
  billingCountry: string | null;
  billingPostalCode: string | null;
  total: number;
}

interface InvoiceLine {
  invoiceLineId: number;
  invoiceId: number;
  trackId: number;
  unitPrice: number;
  quantity: number;
}

interface MediaType {
  mediaTypeId: number;
  name: string | null;
}

interface Playlist {
  playlistId: number;
  name: string | null;
}

interface PlaylistTrack {
  playlistId: number;
  trackId: number;
}

interface Track {
  trackId: number;
  name: string;
  albumId: number | null;
  mediaTypeId: number;
  genreId: number | null;
  composer: string | null;
  milliseconds: number;
  bytes: number | null;
  unitPrice: number;
}

interface Nested<T, U = Partial<T>> {
  create?: T | T[];
  createMany?: { data: T[] };
  connect?: { id: string } | { id: string }[];
  connectOrCreate?:
    | { where: { id: string }; create: T }
    | { where: { id: string }; create: T }[];
  update?:
    | { where: { id: string }; data: U }
    | { where: { id: string }; data: U }[];
  updateMany?: { where: unknown; data: U } | { where: unknown; data: U }[];
  upsert?:
    | { where: { id: string }; create: T; update: U }
    | { where: { id: string }; create: T; update: U }[];
  delete?: boolean | { id: string } | { id: string }[];
  deleteMany?: { where: unknown } | { where: unknown }[];
  set?: { id: string } | { id: string }[];
  disconnect?: boolean | { id: string } | { id: string }[];
}

interface AlbumInclude {
  artist?:
    | boolean
    | {
        where?: ArtistWhere;
        include?: ArtistInclude;
        select?: ArtistSelect;
        take?: number;
        skip?: number;
        orderBy?: ArtistOrderBy | ArtistOrderBy[];
      };
  track?:
    | boolean
    | {
        where?: TrackWhere;
        include?: TrackInclude;
        select?: TrackSelect;
        take?: number;
        skip?: number;
        orderBy?: TrackOrderBy | TrackOrderBy[];
      };
}

interface ArtistInclude {
  album?:
    | boolean
    | {
        where?: AlbumWhere;
        include?: AlbumInclude;
        select?: AlbumSelect;
        take?: number;
        skip?: number;
        orderBy?: AlbumOrderBy | AlbumOrderBy[];
      };
}

interface CustomerInclude {
  employee?:
    | boolean
    | {
        where?: EmployeeWhere;
        include?: EmployeeInclude;
        select?: EmployeeSelect;
        take?: number;
        skip?: number;
        orderBy?: EmployeeOrderBy | EmployeeOrderBy[];
      };
  invoice?:
    | boolean
    | {
        where?: InvoiceWhere;
        include?: InvoiceInclude;
        select?: InvoiceSelect;
        take?: number;
        skip?: number;
        orderBy?: InvoiceOrderBy | InvoiceOrderBy[];
      };
}

interface EmployeeInclude {
  customer?:
    | boolean
    | {
        where?: CustomerWhere;
        include?: CustomerInclude;
        select?: CustomerSelect;
        take?: number;
        skip?: number;
        orderBy?: CustomerOrderBy | CustomerOrderBy[];
      };
  employee?:
    | boolean
    | {
        where?: EmployeeWhere;
        include?: EmployeeInclude;
        select?: EmployeeSelect;
        take?: number;
        skip?: number;
        orderBy?: EmployeeOrderBy | EmployeeOrderBy[];
      };
  otherEmployee?:
    | boolean
    | {
        where?: EmployeeWhere;
        include?: EmployeeInclude;
        select?: EmployeeSelect;
        take?: number;
        skip?: number;
        orderBy?: EmployeeOrderBy | EmployeeOrderBy[];
      };
}

interface GenreInclude {
  track?:
    | boolean
    | {
        where?: TrackWhere;
        include?: TrackInclude;
        select?: TrackSelect;
        take?: number;
        skip?: number;
        orderBy?: TrackOrderBy | TrackOrderBy[];
      };
}

interface InvoiceInclude {
  customer?:
    | boolean
    | {
        where?: CustomerWhere;
        include?: CustomerInclude;
        select?: CustomerSelect;
        take?: number;
        skip?: number;
        orderBy?: CustomerOrderBy | CustomerOrderBy[];
      };
  invoiceLine?:
    | boolean
    | {
        where?: InvoiceLineWhere;
        include?: InvoiceLineInclude;
        select?: InvoiceLineSelect;
        take?: number;
        skip?: number;
        orderBy?: InvoiceLineOrderBy | InvoiceLineOrderBy[];
      };
}

interface InvoiceLineInclude {
  track?:
    | boolean
    | {
        where?: TrackWhere;
        include?: TrackInclude;
        select?: TrackSelect;
        take?: number;
        skip?: number;
        orderBy?: TrackOrderBy | TrackOrderBy[];
      };
  invoice?:
    | boolean
    | {
        where?: InvoiceWhere;
        include?: InvoiceInclude;
        select?: InvoiceSelect;
        take?: number;
        skip?: number;
        orderBy?: InvoiceOrderBy | InvoiceOrderBy[];
      };
}

interface MediaTypeInclude {
  track?:
    | boolean
    | {
        where?: TrackWhere;
        include?: TrackInclude;
        select?: TrackSelect;
        take?: number;
        skip?: number;
        orderBy?: TrackOrderBy | TrackOrderBy[];
      };
}

interface PlaylistInclude {
  playlistTrack?:
    | boolean
    | {
        where?: PlaylistTrackWhere;
        include?: PlaylistTrackInclude;
        select?: PlaylistTrackSelect;
        take?: number;
        skip?: number;
        orderBy?: PlaylistTrackOrderBy | PlaylistTrackOrderBy[];
      };
}

interface PlaylistTrackInclude {
  track?:
    | boolean
    | {
        where?: TrackWhere;
        include?: TrackInclude;
        select?: TrackSelect;
        take?: number;
        skip?: number;
        orderBy?: TrackOrderBy | TrackOrderBy[];
      };
  playlist?:
    | boolean
    | {
        where?: PlaylistWhere;
        include?: PlaylistInclude;
        select?: PlaylistSelect;
        take?: number;
        skip?: number;
        orderBy?: PlaylistOrderBy | PlaylistOrderBy[];
      };
}

interface TrackInclude {
  invoiceLine?:
    | boolean
    | {
        where?: InvoiceLineWhere;
        include?: InvoiceLineInclude;
        select?: InvoiceLineSelect;
        take?: number;
        skip?: number;
        orderBy?: InvoiceLineOrderBy | InvoiceLineOrderBy[];
      };
  playlistTrack?:
    | boolean
    | {
        where?: PlaylistTrackWhere;
        include?: PlaylistTrackInclude;
        select?: PlaylistTrackSelect;
        take?: number;
        skip?: number;
        orderBy?: PlaylistTrackOrderBy | PlaylistTrackOrderBy[];
      };
  mediaType?:
    | boolean
    | {
        where?: MediaTypeWhere;
        include?: MediaTypeInclude;
        select?: MediaTypeSelect;
        take?: number;
        skip?: number;
        orderBy?: MediaTypeOrderBy | MediaTypeOrderBy[];
      };
  genre?:
    | boolean
    | {
        where?: GenreWhere;
        include?: GenreInclude;
        select?: GenreSelect;
        take?: number;
        skip?: number;
        orderBy?: GenreOrderBy | GenreOrderBy[];
      };
  album?:
    | boolean
    | {
        where?: AlbumWhere;
        include?: AlbumInclude;
        select?: AlbumSelect;
        take?: number;
        skip?: number;
        orderBy?: AlbumOrderBy | AlbumOrderBy[];
      };
}

interface AlbumSelect {
  albumId?: boolean;
  title?: boolean;
  artistId?: boolean;
  artist?:
    | boolean
    | {
        where?: ArtistWhere;
        select?: ArtistSelect;
        include?: ArtistInclude;
        take?: number;
        skip?: number;
        orderBy?: ArtistOrderBy | ArtistOrderBy[];
      };
  track?:
    | boolean
    | {
        where?: TrackWhere;
        select?: TrackSelect;
        include?: TrackInclude;
        take?: number;
        skip?: number;
        orderBy?: TrackOrderBy | TrackOrderBy[];
      };
}

interface ArtistSelect {
  artistId?: boolean;
  name?: boolean;
  album?:
    | boolean
    | {
        where?: AlbumWhere;
        select?: AlbumSelect;
        include?: AlbumInclude;
        take?: number;
        skip?: number;
        orderBy?: AlbumOrderBy | AlbumOrderBy[];
      };
}

interface CustomerSelect {
  customerId?: boolean;
  firstName?: boolean;
  lastName?: boolean;
  company?: boolean;
  address?: boolean;
  city?: boolean;
  state?: boolean;
  country?: boolean;
  postalCode?: boolean;
  phone?: boolean;
  fax?: boolean;
  email?: boolean;
  supportRepId?: boolean;
  employee?:
    | boolean
    | {
        where?: EmployeeWhere;
        select?: EmployeeSelect;
        include?: EmployeeInclude;
        take?: number;
        skip?: number;
        orderBy?: EmployeeOrderBy | EmployeeOrderBy[];
      };
  invoice?:
    | boolean
    | {
        where?: InvoiceWhere;
        select?: InvoiceSelect;
        include?: InvoiceInclude;
        take?: number;
        skip?: number;
        orderBy?: InvoiceOrderBy | InvoiceOrderBy[];
      };
}

interface EmployeeSelect {
  employeeId?: boolean;
  lastName?: boolean;
  firstName?: boolean;
  title?: boolean;
  reportsTo?: boolean;
  birthDate?: boolean;
  hireDate?: boolean;
  address?: boolean;
  city?: boolean;
  state?: boolean;
  country?: boolean;
  postalCode?: boolean;
  phone?: boolean;
  fax?: boolean;
  email?: boolean;
  customer?:
    | boolean
    | {
        where?: CustomerWhere;
        select?: CustomerSelect;
        include?: CustomerInclude;
        take?: number;
        skip?: number;
        orderBy?: CustomerOrderBy | CustomerOrderBy[];
      };
  employee?:
    | boolean
    | {
        where?: EmployeeWhere;
        select?: EmployeeSelect;
        include?: EmployeeInclude;
        take?: number;
        skip?: number;
        orderBy?: EmployeeOrderBy | EmployeeOrderBy[];
      };
  otherEmployee?:
    | boolean
    | {
        where?: EmployeeWhere;
        select?: EmployeeSelect;
        include?: EmployeeInclude;
        take?: number;
        skip?: number;
        orderBy?: EmployeeOrderBy | EmployeeOrderBy[];
      };
}

interface GenreSelect {
  genreId?: boolean;
  name?: boolean;
  track?:
    | boolean
    | {
        where?: TrackWhere;
        select?: TrackSelect;
        include?: TrackInclude;
        take?: number;
        skip?: number;
        orderBy?: TrackOrderBy | TrackOrderBy[];
      };
}

interface InvoiceSelect {
  invoiceId?: boolean;
  customerId?: boolean;
  invoiceDate?: boolean;
  billingAddress?: boolean;
  billingCity?: boolean;
  billingState?: boolean;
  billingCountry?: boolean;
  billingPostalCode?: boolean;
  total?: boolean;
  customer?:
    | boolean
    | {
        where?: CustomerWhere;
        select?: CustomerSelect;
        include?: CustomerInclude;
        take?: number;
        skip?: number;
        orderBy?: CustomerOrderBy | CustomerOrderBy[];
      };
  invoiceLine?:
    | boolean
    | {
        where?: InvoiceLineWhere;
        select?: InvoiceLineSelect;
        include?: InvoiceLineInclude;
        take?: number;
        skip?: number;
        orderBy?: InvoiceLineOrderBy | InvoiceLineOrderBy[];
      };
}

interface InvoiceLineSelect {
  invoiceLineId?: boolean;
  invoiceId?: boolean;
  trackId?: boolean;
  unitPrice?: boolean;
  quantity?: boolean;
  track?:
    | boolean
    | {
        where?: TrackWhere;
        select?: TrackSelect;
        include?: TrackInclude;
        take?: number;
        skip?: number;
        orderBy?: TrackOrderBy | TrackOrderBy[];
      };
  invoice?:
    | boolean
    | {
        where?: InvoiceWhere;
        select?: InvoiceSelect;
        include?: InvoiceInclude;
        take?: number;
        skip?: number;
        orderBy?: InvoiceOrderBy | InvoiceOrderBy[];
      };
}

interface MediaTypeSelect {
  mediaTypeId?: boolean;
  name?: boolean;
  track?:
    | boolean
    | {
        where?: TrackWhere;
        select?: TrackSelect;
        include?: TrackInclude;
        take?: number;
        skip?: number;
        orderBy?: TrackOrderBy | TrackOrderBy[];
      };
}

interface PlaylistSelect {
  playlistId?: boolean;
  name?: boolean;
  playlistTrack?:
    | boolean
    | {
        where?: PlaylistTrackWhere;
        select?: PlaylistTrackSelect;
        include?: PlaylistTrackInclude;
        take?: number;
        skip?: number;
        orderBy?: PlaylistTrackOrderBy | PlaylistTrackOrderBy[];
      };
}

interface PlaylistTrackSelect {
  playlistId?: boolean;
  trackId?: boolean;
  track?:
    | boolean
    | {
        where?: TrackWhere;
        select?: TrackSelect;
        include?: TrackInclude;
        take?: number;
        skip?: number;
        orderBy?: TrackOrderBy | TrackOrderBy[];
      };
  playlist?:
    | boolean
    | {
        where?: PlaylistWhere;
        select?: PlaylistSelect;
        include?: PlaylistInclude;
        take?: number;
        skip?: number;
        orderBy?: PlaylistOrderBy | PlaylistOrderBy[];
      };
}

interface TrackSelect {
  trackId?: boolean;
  name?: boolean;
  albumId?: boolean;
  mediaTypeId?: boolean;
  genreId?: boolean;
  composer?: boolean;
  milliseconds?: boolean;
  bytes?: boolean;
  unitPrice?: boolean;
  invoiceLine?:
    | boolean
    | {
        where?: InvoiceLineWhere;
        select?: InvoiceLineSelect;
        include?: InvoiceLineInclude;
        take?: number;
        skip?: number;
        orderBy?: InvoiceLineOrderBy | InvoiceLineOrderBy[];
      };
  playlistTrack?:
    | boolean
    | {
        where?: PlaylistTrackWhere;
        select?: PlaylistTrackSelect;
        include?: PlaylistTrackInclude;
        take?: number;
        skip?: number;
        orderBy?: PlaylistTrackOrderBy | PlaylistTrackOrderBy[];
      };
  mediaType?:
    | boolean
    | {
        where?: MediaTypeWhere;
        select?: MediaTypeSelect;
        include?: MediaTypeInclude;
        take?: number;
        skip?: number;
        orderBy?: MediaTypeOrderBy | MediaTypeOrderBy[];
      };
  genre?:
    | boolean
    | {
        where?: GenreWhere;
        select?: GenreSelect;
        include?: GenreInclude;
        take?: number;
        skip?: number;
        orderBy?: GenreOrderBy | GenreOrderBy[];
      };
  album?:
    | boolean
    | {
        where?: AlbumWhere;
        select?: AlbumSelect;
        include?: AlbumInclude;
        take?: number;
        skip?: number;
        orderBy?: AlbumOrderBy | AlbumOrderBy[];
      };
}

interface StringFilter {
  equals?: string;
  not?: string | StringFilter;
  in?: string[];
  notIn?: string[];
  lt?: string;
  lte?: string;
  gt?: string;
  gte?: string;
  contains?: string;
  startsWith?: string;
  endsWith?: string;
}
type StringWhere = string | StringFilter;
interface StringNullableFilter {
  equals?: string | null;
  not?: string | null | StringNullableFilter;
  in?: string[];
  notIn?: string[];
  lt?: string;
  lte?: string;
  gt?: string;
  gte?: string;
  contains?: string;
  startsWith?: string;
  endsWith?: string;
}
type StringNullableWhere = string | null | StringNullableFilter;

interface NumberFilter {
  equals?: number;
  not?: number | NumberFilter;
  in?: number[];
  notIn?: number[];
  lt?: number;
  lte?: number;
  gt?: number;
  gte?: number;
}
type NumberWhere = number | NumberFilter;
interface NumberNullableFilter {
  equals?: number | null;
  not?: number | null | NumberNullableFilter;
  in?: number[];
  notIn?: number[];
  lt?: number;
  lte?: number;
  gt?: number;
  gte?: number;
}
type NumberNullableWhere = number | null | NumberNullableFilter;

interface BooleanFilter {
  equals?: boolean;
  not?: boolean | BooleanFilter;
}
type BooleanWhere = boolean | BooleanFilter;
type BooleanNullableWhere = boolean | null | BooleanFilter;

type DateTimeWhere = StringWhere;
type DateTimeNullableWhere = StringNullableWhere;
type BytesWhere = Uint8Array | { equals?: Uint8Array; not?: Uint8Array };
type JsonWhere = unknown;

interface AlbumWhere {
  AND?: AlbumWhere | AlbumWhere[];
  OR?: AlbumWhere[];
  NOT?: AlbumWhere | AlbumWhere[];
  albumId?: NumberWhere;
  title?: StringWhere;
  artistId?: NumberWhere;
  artist?: ArtistWhere | { is?: ArtistWhere; isNot?: ArtistWhere };
  track?: { some?: TrackWhere; every?: TrackWhere; none?: TrackWhere };
}

interface ArtistWhere {
  AND?: ArtistWhere | ArtistWhere[];
  OR?: ArtistWhere[];
  NOT?: ArtistWhere | ArtistWhere[];
  artistId?: NumberWhere;
  name?: StringNullableWhere;
  album?: { some?: AlbumWhere; every?: AlbumWhere; none?: AlbumWhere };
}

interface CustomerWhere {
  AND?: CustomerWhere | CustomerWhere[];
  OR?: CustomerWhere[];
  NOT?: CustomerWhere | CustomerWhere[];
  customerId?: NumberWhere;
  firstName?: StringWhere;
  lastName?: StringWhere;
  company?: StringNullableWhere;
  address?: StringNullableWhere;
  city?: StringNullableWhere;
  state?: StringNullableWhere;
  country?: StringNullableWhere;
  postalCode?: StringNullableWhere;
  phone?: StringNullableWhere;
  fax?: StringNullableWhere;
  email?: StringWhere;
  supportRepId?: NumberNullableWhere;
  employee?:
    | EmployeeWhere
    | { is?: EmployeeWhere | null; isNot?: EmployeeWhere | null };
  invoice?: { some?: InvoiceWhere; every?: InvoiceWhere; none?: InvoiceWhere };
}

interface EmployeeWhere {
  AND?: EmployeeWhere | EmployeeWhere[];
  OR?: EmployeeWhere[];
  NOT?: EmployeeWhere | EmployeeWhere[];
  employeeId?: NumberWhere;
  lastName?: StringWhere;
  firstName?: StringWhere;
  title?: StringNullableWhere;
  reportsTo?: NumberNullableWhere;
  birthDate?: StringNullableWhere;
  hireDate?: StringNullableWhere;
  address?: StringNullableWhere;
  city?: StringNullableWhere;
  state?: StringNullableWhere;
  country?: StringNullableWhere;
  postalCode?: StringNullableWhere;
  phone?: StringNullableWhere;
  fax?: StringNullableWhere;
  email?: StringNullableWhere;
  customer?: {
    some?: CustomerWhere;
    every?: CustomerWhere;
    none?: CustomerWhere;
  };
  employee?:
    | EmployeeWhere
    | { is?: EmployeeWhere | null; isNot?: EmployeeWhere | null };
  otherEmployee?: {
    some?: EmployeeWhere;
    every?: EmployeeWhere;
    none?: EmployeeWhere;
  };
}

interface GenreWhere {
  AND?: GenreWhere | GenreWhere[];
  OR?: GenreWhere[];
  NOT?: GenreWhere | GenreWhere[];
  genreId?: NumberWhere;
  name?: StringNullableWhere;
  track?: { some?: TrackWhere; every?: TrackWhere; none?: TrackWhere };
}

interface InvoiceWhere {
  AND?: InvoiceWhere | InvoiceWhere[];
  OR?: InvoiceWhere[];
  NOT?: InvoiceWhere | InvoiceWhere[];
  invoiceId?: NumberWhere;
  customerId?: NumberWhere;
  invoiceDate?: StringWhere;
  billingAddress?: StringNullableWhere;
  billingCity?: StringNullableWhere;
  billingState?: StringNullableWhere;
  billingCountry?: StringNullableWhere;
  billingPostalCode?: StringNullableWhere;
  total?: NumberWhere;
  customer?: CustomerWhere | { is?: CustomerWhere; isNot?: CustomerWhere };
  invoiceLine?: {
    some?: InvoiceLineWhere;
    every?: InvoiceLineWhere;
    none?: InvoiceLineWhere;
  };
}

interface InvoiceLineWhere {
  AND?: InvoiceLineWhere | InvoiceLineWhere[];
  OR?: InvoiceLineWhere[];
  NOT?: InvoiceLineWhere | InvoiceLineWhere[];
  invoiceLineId?: NumberWhere;
  invoiceId?: NumberWhere;
  trackId?: NumberWhere;
  unitPrice?: NumberWhere;
  quantity?: NumberWhere;
  track?: TrackWhere | { is?: TrackWhere; isNot?: TrackWhere };
  invoice?: InvoiceWhere | { is?: InvoiceWhere; isNot?: InvoiceWhere };
}

interface MediaTypeWhere {
  AND?: MediaTypeWhere | MediaTypeWhere[];
  OR?: MediaTypeWhere[];
  NOT?: MediaTypeWhere | MediaTypeWhere[];
  mediaTypeId?: NumberWhere;
  name?: StringNullableWhere;
  track?: { some?: TrackWhere; every?: TrackWhere; none?: TrackWhere };
}

interface PlaylistWhere {
  AND?: PlaylistWhere | PlaylistWhere[];
  OR?: PlaylistWhere[];
  NOT?: PlaylistWhere | PlaylistWhere[];
  playlistId?: NumberWhere;
  name?: StringNullableWhere;
  playlistTrack?: {
    some?: PlaylistTrackWhere;
    every?: PlaylistTrackWhere;
    none?: PlaylistTrackWhere;
  };
}

interface PlaylistTrackWhere {
  AND?: PlaylistTrackWhere | PlaylistTrackWhere[];
  OR?: PlaylistTrackWhere[];
  NOT?: PlaylistTrackWhere | PlaylistTrackWhere[];
  playlistId?: NumberWhere;
  trackId?: NumberWhere;
  track?: TrackWhere | { is?: TrackWhere; isNot?: TrackWhere };
  playlist?: PlaylistWhere | { is?: PlaylistWhere; isNot?: PlaylistWhere };
}

interface TrackWhere {
  AND?: TrackWhere | TrackWhere[];
  OR?: TrackWhere[];
  NOT?: TrackWhere | TrackWhere[];
  trackId?: NumberWhere;
  name?: StringWhere;
  albumId?: NumberNullableWhere;
  mediaTypeId?: NumberWhere;
  genreId?: NumberNullableWhere;
  composer?: StringNullableWhere;
  milliseconds?: NumberWhere;
  bytes?: NumberNullableWhere;
  unitPrice?: NumberWhere;
  invoiceLine?: {
    some?: InvoiceLineWhere;
    every?: InvoiceLineWhere;
    none?: InvoiceLineWhere;
  };
  playlistTrack?: {
    some?: PlaylistTrackWhere;
    every?: PlaylistTrackWhere;
    none?: PlaylistTrackWhere;
  };
  mediaType?: MediaTypeWhere | { is?: MediaTypeWhere; isNot?: MediaTypeWhere };
  genre?: GenreWhere | { is?: GenreWhere | null; isNot?: GenreWhere | null };
  album?: AlbumWhere | { is?: AlbumWhere | null; isNot?: AlbumWhere | null };
}

interface AlbumOrderBy {
  albumId?: OrderByField;
  title?: OrderByField;
  artistId?: OrderByField;
  artist?: ArtistOrderBy;
  track?: { _count?: OrderByField };
}

interface ArtistOrderBy {
  artistId?: OrderByField;
  name?: OrderByField;
  album?: { _count?: OrderByField };
}

interface CustomerOrderBy {
  customerId?: OrderByField;
  firstName?: OrderByField;
  lastName?: OrderByField;
  company?: OrderByField;
  address?: OrderByField;
  city?: OrderByField;
  state?: OrderByField;
  country?: OrderByField;
  postalCode?: OrderByField;
  phone?: OrderByField;
  fax?: OrderByField;
  email?: OrderByField;
  supportRepId?: OrderByField;
  employee?: EmployeeOrderBy;
  invoice?: { _count?: OrderByField };
}

interface EmployeeOrderBy {
  employeeId?: OrderByField;
  lastName?: OrderByField;
  firstName?: OrderByField;
  title?: OrderByField;
  reportsTo?: OrderByField;
  birthDate?: OrderByField;
  hireDate?: OrderByField;
  address?: OrderByField;
  city?: OrderByField;
  state?: OrderByField;
  country?: OrderByField;
  postalCode?: OrderByField;
  phone?: OrderByField;
  fax?: OrderByField;
  email?: OrderByField;
  customer?: { _count?: OrderByField };
  employee?: EmployeeOrderBy;
  otherEmployee?: { _count?: OrderByField };
}

interface GenreOrderBy {
  genreId?: OrderByField;
  name?: OrderByField;
  track?: { _count?: OrderByField };
}

interface InvoiceOrderBy {
  invoiceId?: OrderByField;
  customerId?: OrderByField;
  invoiceDate?: OrderByField;
  billingAddress?: OrderByField;
  billingCity?: OrderByField;
  billingState?: OrderByField;
  billingCountry?: OrderByField;
  billingPostalCode?: OrderByField;
  total?: OrderByField;
  customer?: CustomerOrderBy;
  invoiceLine?: { _count?: OrderByField };
}

interface InvoiceLineOrderBy {
  invoiceLineId?: OrderByField;
  invoiceId?: OrderByField;
  trackId?: OrderByField;
  unitPrice?: OrderByField;
  quantity?: OrderByField;
  track?: TrackOrderBy;
  invoice?: InvoiceOrderBy;
}

interface MediaTypeOrderBy {
  mediaTypeId?: OrderByField;
  name?: OrderByField;
  track?: { _count?: OrderByField };
}

interface PlaylistOrderBy {
  playlistId?: OrderByField;
  name?: OrderByField;
  playlistTrack?: { _count?: OrderByField };
}

interface PlaylistTrackOrderBy {
  playlistId?: OrderByField;
  trackId?: OrderByField;
  track?: TrackOrderBy;
  playlist?: PlaylistOrderBy;
}

interface TrackOrderBy {
  trackId?: OrderByField;
  name?: OrderByField;
  albumId?: OrderByField;
  mediaTypeId?: OrderByField;
  genreId?: OrderByField;
  composer?: OrderByField;
  milliseconds?: OrderByField;
  bytes?: OrderByField;
  unitPrice?: OrderByField;
  invoiceLine?: { _count?: OrderByField };
  playlistTrack?: { _count?: OrderByField };
  mediaType?: MediaTypeOrderBy;
  genre?: GenreOrderBy;
  album?: AlbumOrderBy;
}

interface AlbumCreateInput {
  albumId?: number;
  title: string;
  artistId?: number;
  artist?: Nested<ArtistCreateInput, ArtistUpdateInput>;
  track?: Nested<TrackCreateInput, TrackUpdateInput>;
}

interface ArtistCreateInput {
  artistId?: number;
  name?: string | null;
  album?: Nested<AlbumCreateInput, AlbumUpdateInput>;
}

interface CustomerCreateInput {
  customerId?: number;
  firstName: string;
  lastName: string;
  company?: string | null;
  address?: string | null;
  city?: string | null;
  state?: string | null;
  country?: string | null;
  postalCode?: string | null;
  phone?: string | null;
  fax?: string | null;
  email: string;
  supportRepId?: number | null;
  employee?: Nested<EmployeeCreateInput, EmployeeUpdateInput>;
  invoice?: Nested<InvoiceCreateInput, InvoiceUpdateInput>;
}

interface EmployeeCreateInput {
  employeeId?: number;
  lastName: string;
  firstName: string;
  title?: string | null;
  reportsTo?: number | null;
  birthDate?: string | null;
  hireDate?: string | null;
  address?: string | null;
  city?: string | null;
  state?: string | null;
  country?: string | null;
  postalCode?: string | null;
  phone?: string | null;
  fax?: string | null;
  email?: string | null;
  customer?: Nested<CustomerCreateInput, CustomerUpdateInput>;
  employee?: Nested<EmployeeCreateInput, EmployeeUpdateInput>;
  otherEmployee?: Nested<EmployeeCreateInput, EmployeeUpdateInput>;
}

interface GenreCreateInput {
  genreId?: number;
  name?: string | null;
  track?: Nested<TrackCreateInput, TrackUpdateInput>;
}

interface InvoiceCreateInput {
  invoiceId?: number;
  customerId?: number;
  invoiceDate: string;
  billingAddress?: string | null;
  billingCity?: string | null;
  billingState?: string | null;
  billingCountry?: string | null;
  billingPostalCode?: string | null;
  total: number;
  customer?: Nested<CustomerCreateInput, CustomerUpdateInput>;
  invoiceLine?: Nested<InvoiceLineCreateInput, InvoiceLineUpdateInput>;
}

interface InvoiceLineCreateInput {
  invoiceLineId?: number;
  invoiceId?: number;
  trackId?: number;
  unitPrice: number;
  quantity: number;
  track?: Nested<TrackCreateInput, TrackUpdateInput>;
  invoice?: Nested<InvoiceCreateInput, InvoiceUpdateInput>;
}

interface MediaTypeCreateInput {
  mediaTypeId?: number;
  name?: string | null;
  track?: Nested<TrackCreateInput, TrackUpdateInput>;
}

interface PlaylistCreateInput {
  playlistId?: number;
  name?: string | null;
  playlistTrack?: Nested<PlaylistTrackCreateInput, PlaylistTrackUpdateInput>;
}

interface PlaylistTrackCreateInput {
  playlistId?: number;
  trackId?: number;
  track?: Nested<TrackCreateInput, TrackUpdateInput>;
  playlist?: Nested<PlaylistCreateInput, PlaylistUpdateInput>;
}

interface TrackCreateInput {
  trackId?: number;
  name: string;
  albumId?: number | null;
  mediaTypeId?: number;
  genreId?: number | null;
  composer?: string | null;
  milliseconds: number;
  bytes?: number | null;
  unitPrice: number;
  invoiceLine?: Nested<InvoiceLineCreateInput, InvoiceLineUpdateInput>;
  playlistTrack?: Nested<PlaylistTrackCreateInput, PlaylistTrackUpdateInput>;
  mediaType?: Nested<MediaTypeCreateInput, MediaTypeUpdateInput>;
  genre?: Nested<GenreCreateInput, GenreUpdateInput>;
  album?: Nested<AlbumCreateInput, AlbumUpdateInput>;
}

interface AlbumUpdateInput {
  albumId?: number;
  title?: string;
  artistId?: number;
  artist?: Nested<ArtistCreateInput, ArtistUpdateInput>;
  track?: Nested<TrackCreateInput, TrackUpdateInput>;
}

interface ArtistUpdateInput {
  artistId?: number;
  name?: string | null;
  album?: Nested<AlbumCreateInput, AlbumUpdateInput>;
}

interface CustomerUpdateInput {
  customerId?: number;
  firstName?: string;
  lastName?: string;
  company?: string | null;
  address?: string | null;
  city?: string | null;
  state?: string | null;
  country?: string | null;
  postalCode?: string | null;
  phone?: string | null;
  fax?: string | null;
  email?: string;
  supportRepId?: number | null;
  employee?: Nested<EmployeeCreateInput, EmployeeUpdateInput>;
  invoice?: Nested<InvoiceCreateInput, InvoiceUpdateInput>;
}

interface EmployeeUpdateInput {
  employeeId?: number;
  lastName?: string;
  firstName?: string;
  title?: string | null;
  reportsTo?: number | null;
  birthDate?: string | null;
  hireDate?: string | null;
  address?: string | null;
  city?: string | null;
  state?: string | null;
  country?: string | null;
  postalCode?: string | null;
  phone?: string | null;
  fax?: string | null;
  email?: string | null;
  customer?: Nested<CustomerCreateInput, CustomerUpdateInput>;
  employee?: Nested<EmployeeCreateInput, EmployeeUpdateInput>;
  otherEmployee?: Nested<EmployeeCreateInput, EmployeeUpdateInput>;
}

interface GenreUpdateInput {
  genreId?: number;
  name?: string | null;
  track?: Nested<TrackCreateInput, TrackUpdateInput>;
}

interface InvoiceUpdateInput {
  invoiceId?: number;
  customerId?: number;
  invoiceDate?: string;
  billingAddress?: string | null;
  billingCity?: string | null;
  billingState?: string | null;
  billingCountry?: string | null;
  billingPostalCode?: string | null;
  total?: number;
  customer?: Nested<CustomerCreateInput, CustomerUpdateInput>;
  invoiceLine?: Nested<InvoiceLineCreateInput, InvoiceLineUpdateInput>;
}

interface InvoiceLineUpdateInput {
  invoiceLineId?: number;
  invoiceId?: number;
  trackId?: number;
  unitPrice?: number;
  quantity?: number;
  track?: Nested<TrackCreateInput, TrackUpdateInput>;
  invoice?: Nested<InvoiceCreateInput, InvoiceUpdateInput>;
}

interface MediaTypeUpdateInput {
  mediaTypeId?: number;
  name?: string | null;
  track?: Nested<TrackCreateInput, TrackUpdateInput>;
}

interface PlaylistUpdateInput {
  playlistId?: number;
  name?: string | null;
  playlistTrack?: Nested<PlaylistTrackCreateInput, PlaylistTrackUpdateInput>;
}

interface PlaylistTrackUpdateInput {
  playlistId?: number;
  trackId?: number;
  track?: Nested<TrackCreateInput, TrackUpdateInput>;
  playlist?: Nested<PlaylistCreateInput, PlaylistUpdateInput>;
}

interface TrackUpdateInput {
  trackId?: number;
  name?: string;
  albumId?: number | null;
  mediaTypeId?: number;
  genreId?: number | null;
  composer?: string | null;
  milliseconds?: number;
  bytes?: number | null;
  unitPrice?: number;
  invoiceLine?: Nested<InvoiceLineCreateInput, InvoiceLineUpdateInput>;
  playlistTrack?: Nested<PlaylistTrackCreateInput, PlaylistTrackUpdateInput>;
  mediaType?: Nested<MediaTypeCreateInput, MediaTypeUpdateInput>;
  genre?: Nested<GenreCreateInput, GenreUpdateInput>;
  album?: Nested<AlbumCreateInput, AlbumUpdateInput>;
}

type OrderByField = 'asc' | 'desc';

interface FindManyArgs<W, I, S, O> {
  where?: W;
  orderBy?: O | O[];
  take?: number;
  skip?: number;
  include?: I;
  select?: S;
}

interface FindUniqueArgs<W, I, S> {
  where: W;
  include?: I;
  select?: S;
}

interface CreateArgs<D, I, S> {
  data: D;
  include?: I;
  select?: S;
}

interface UpdateArgs<W, D, I, S> {
  where: W;
  data: D;
  include?: I;
  select?: S;
}

interface DeleteArgs<W, I, S> {
  where: W;
  include?: I;
  select?: S;
}

interface Delegate<T, W, C, U, I, S, O> {
  findMany(args?: FindManyArgs<W, I, S, O>): Promise<T[]>;
  findFirst(args?: FindManyArgs<W, I, S, O>): Promise<T | null>;
  findFirstOrThrow(args?: FindManyArgs<W, I, S, O>): Promise<T>;
  findUnique(args: FindUniqueArgs<W, I, S>): Promise<T | null>;
  findUniqueOrThrow(args: FindUniqueArgs<W, I, S>): Promise<T>;
  create(args: CreateArgs<C, I, S>): Promise<T>;
  createMany(args: { data: C[] }): Promise<{ count: number }>;
  createManyAndReturn(args: { data: C[] }): Promise<T[]>;
  update(args: UpdateArgs<W, U, I, S>): Promise<T>;
  updateMany(args: { where?: W; data: U }): Promise<{ count: number }>;
  upsert(args: {
    where: W;
    create: C;
    update: U;
    include?: I;
    select?: S;
  }): Promise<T>;
  delete(args: DeleteArgs<W, I, S>): Promise<T>;
  deleteMany(args?: { where?: W }): Promise<{ count: number }>;
  count(args?: { where?: W }): Promise<number>;
  aggregate(args?: {
    where?: W;
    _count?: boolean;
    _min?: Record<string, boolean>;
    _max?: Record<string, boolean>;
  }): Promise<Record<string, unknown>>;
  groupBy(args: {
    by: string[];
    where?: W;
    _count?: boolean;
  }): Promise<Record<string, unknown>[]>;
}

interface DB {
  album: Delegate<
    Album,
    AlbumWhere,
    AlbumCreateInput,
    AlbumUpdateInput,
    AlbumInclude,
    AlbumSelect,
    AlbumOrderBy
  >;
  artist: Delegate<
    Artist,
    ArtistWhere,
    ArtistCreateInput,
    ArtistUpdateInput,
    ArtistInclude,
    ArtistSelect,
    ArtistOrderBy
  >;
  customer: Delegate<
    Customer,
    CustomerWhere,
    CustomerCreateInput,
    CustomerUpdateInput,
    CustomerInclude,
    CustomerSelect,
    CustomerOrderBy
  >;
  employee: Delegate<
    Employee,
    EmployeeWhere,
    EmployeeCreateInput,
    EmployeeUpdateInput,
    EmployeeInclude,
    EmployeeSelect,
    EmployeeOrderBy
  >;
  genre: Delegate<
    Genre,
    GenreWhere,
    GenreCreateInput,
    GenreUpdateInput,
    GenreInclude,
    GenreSelect,
    GenreOrderBy
  >;
  invoice: Delegate<
    Invoice,
    InvoiceWhere,
    InvoiceCreateInput,
    InvoiceUpdateInput,
    InvoiceInclude,
    InvoiceSelect,
    InvoiceOrderBy
  >;
  invoiceLine: Delegate<
    InvoiceLine,
    InvoiceLineWhere,
    InvoiceLineCreateInput,
    InvoiceLineUpdateInput,
    InvoiceLineInclude,
    InvoiceLineSelect,
    InvoiceLineOrderBy
  >;
  mediaType: Delegate<
    MediaType,
    MediaTypeWhere,
    MediaTypeCreateInput,
    MediaTypeUpdateInput,
    MediaTypeInclude,
    MediaTypeSelect,
    MediaTypeOrderBy
  >;
  playlist: Delegate<
    Playlist,
    PlaylistWhere,
    PlaylistCreateInput,
    PlaylistUpdateInput,
    PlaylistInclude,
    PlaylistSelect,
    PlaylistOrderBy
  >;
  playlistTrack: Delegate<
    PlaylistTrack,
    PlaylistTrackWhere,
    PlaylistTrackCreateInput,
    PlaylistTrackUpdateInput,
    PlaylistTrackInclude,
    PlaylistTrackSelect,
    PlaylistTrackOrderBy
  >;
  track: Delegate<
    Track,
    TrackWhere,
    TrackCreateInput,
    TrackUpdateInput,
    TrackInclude,
    TrackSelect,
    TrackOrderBy
  >;
  $transaction<T>(fn: (tx: DB) => Promise<T>): Promise<T>;
  $executeRawUnsafe(sql: string, ...args: unknown[]): Promise<number>;
  $queryRawUnsafe(sql: string, ...args: unknown[]): Promise<unknown>;
}
