/**
 * Generate slim TypeScript declarations for the Prisma REPL's Monaco editor.
 *
 * Reads prisma/schema.prisma, extracts models (scalars + relations),
 * and writes prisma/repl-types.d.ts with per-model row/create/update/include
 * types so nested writes and `include` get autocomplete.
 *
 * Usage: node --experimental-transform-types scripts/generate-repl-types.ts
 */

import { readFileSync, writeFileSync } from 'fs';
import { resolve } from 'path';

const schemaPath = resolve(import.meta.dirname, '../prisma/schema.prisma');
const schema = readFileSync(schemaPath, 'utf-8');

interface ScalarField {
  name: string;
  type: string;
  optional: boolean;
  hasDefault: boolean;
}

interface RelationField {
  name: string;
  target: string;
  list: boolean;
  optional: boolean;
  fkFields: string[];
}

interface Model {
  name: string;
  scalars: ScalarField[];
  relations: RelationField[];
  fkFields: Set<string>;
}

const SCALAR_TYPES = new Set([
  'String',
  'Int',
  'Float',
  'Boolean',
  'DateTime',
  'Bytes',
  'BigInt',
  'Decimal',
  'Json',
]);

const MANAGED_OPTIONAL = new Set([
  'id',
  'seq',
  'createdBy',
  'createdAt',
  'deletedAt',
]);

function mapScalar(prismaType: string): string {
  switch (prismaType) {
    case 'String':
      return 'string';
    case 'Int':
    case 'Float':
    case 'Decimal':
      return 'number';
    case 'BigInt':
      return 'bigint';
    case 'Boolean':
      return 'boolean';
    case 'DateTime':
      return 'string';
    case 'Bytes':
      return 'Uint8Array';
    case 'Json':
      return 'unknown';
    default:
      return 'any';
  }
}

function camelCase(name: string): string {
  return name.charAt(0).toLowerCase() + name.slice(1);
}

const models: Model[] = [];
const modelRegex = /^model\s+(\w+)\s*\{([\s\S]*?)^\}/gm;

for (const match of schema.matchAll(modelRegex)) {
  const name = match[1];
  const body = match[2];
  const scalars: ScalarField[] = [];
  const relations: RelationField[] = [];

  for (const rawLine of body.split('\n')) {
    const line = rawLine.trim();
    if (!line || line.startsWith('//') || line.startsWith('@@')) continue;

    const fieldMatch = line.match(/^(\w+)\s+(\w+)(\[\])?(\?)?(\s.*)?$/);
    if (!fieldMatch) continue;
    const [, fieldName, fieldType, list, opt, rest] = fieldMatch;
    const hasDefault = !!rest && /@default\s*\(/.test(rest);

    if (SCALAR_TYPES.has(fieldType)) {
      scalars.push({
        name: fieldName,
        type: mapScalar(fieldType),
        optional: !!opt,
        hasDefault,
      });
      continue;
    }

    // Relation field
    const fkMatch = rest?.match(/@relation\([^)]*fields:\s*\[([^\]]+)\]/);
    const fkFields = fkMatch ? fkMatch[1].split(',').map((s) => s.trim()) : [];
    relations.push({
      name: fieldName,
      target: fieldType,
      list: !!list,
      optional: !!opt,
      fkFields,
    });
  }

  const fkSet = new Set<string>();
  for (const r of relations) for (const fk of r.fkFields) fkSet.add(fk);

  models.push({ name, scalars, relations, fkFields: fkSet });
}

const lines: string[] = [
  '// Auto-generated by scripts/generate-repl-types.ts — do not edit manually.',
  '// Provides slim type declarations for the Prisma REPL Monaco editor.',
  '',
  'declare const prisma: DB;',
  'declare function randomUUID(): string;',
  '',
];

// Row types
for (const model of models) {
  lines.push(`interface ${model.name} {`);
  for (const f of model.scalars) {
    const type = f.optional ? `${f.type} | null` : f.type;
    lines.push(`  ${f.name}: ${type};`);
  }
  lines.push('}');
  lines.push('');
}

// Nested write wrapper — generic for both one-to-many and one-to-one
lines.push(`interface Nested<T, U = Partial<T>> {
  create?: T | T[];
  createMany?: { data: T[] };
  connect?: { id: string } | { id: string }[];
  connectOrCreate?:
    | { where: { id: string }; create: T }
    | { where: { id: string }; create: T }[];
  update?:
    | { where: { id: string }; data: U }
    | { where: { id: string }; data: U }[];
  updateMany?:
    | { where: unknown; data: U }
    | { where: unknown; data: U }[];
  upsert?:
    | { where: { id: string }; create: T; update: U }
    | { where: { id: string }; create: T; update: U }[];
  delete?: boolean | { id: string } | { id: string }[];
  deleteMany?: { where: unknown } | { where: unknown }[];
  set?: { id: string } | { id: string }[];
  disconnect?: boolean | { id: string } | { id: string }[];
}
`);

// Include types — per model
for (const model of models) {
  if (model.relations.length === 0) {
    lines.push(`type ${model.name}Include = Record<string, never>;`);
    lines.push('');
    continue;
  }
  lines.push(`interface ${model.name}Include {`);
  for (const r of model.relations) {
    const detail = `{ where?: ${r.target}Where; include?: ${r.target}Include; select?: ${r.target}Select; take?: number; skip?: number; orderBy?: ${r.target}OrderBy | ${r.target}OrderBy[] }`;
    lines.push(`  ${r.name}?: boolean | ${detail};`);
  }
  lines.push('}');
  lines.push('');
}

// Select types — per model. Mirrors Include but with `select` as an option
// for relations so callers can drill into nested column projections.
for (const model of models) {
  lines.push(`interface ${model.name}Select {`);
  for (const f of model.scalars) {
    lines.push(`  ${f.name}?: boolean;`);
  }
  for (const r of model.relations) {
    const detail = `{ where?: ${r.target}Where; select?: ${r.target}Select; include?: ${r.target}Include; take?: number; skip?: number; orderBy?: ${r.target}OrderBy | ${r.target}OrderBy[] }`;
    lines.push(`  ${r.name}?: boolean | ${detail};`);
  }
  lines.push('}');
  lines.push('');
}

// Where filter helpers (defined once, reused across all model wheres).
lines.push(`interface StringFilter {
  equals?: string;
  not?: string | StringFilter;
  in?: string[];
  notIn?: string[];
  lt?: string;
  lte?: string;
  gt?: string;
  gte?: string;
  contains?: string;
  startsWith?: string;
  endsWith?: string;
}
type StringWhere = string | StringFilter;
interface StringNullableFilter {
  equals?: string | null;
  not?: string | null | StringNullableFilter;
  in?: string[];
  notIn?: string[];
  lt?: string;
  lte?: string;
  gt?: string;
  gte?: string;
  contains?: string;
  startsWith?: string;
  endsWith?: string;
}
type StringNullableWhere = string | null | StringNullableFilter;

interface NumberFilter {
  equals?: number;
  not?: number | NumberFilter;
  in?: number[];
  notIn?: number[];
  lt?: number;
  lte?: number;
  gt?: number;
  gte?: number;
}
type NumberWhere = number | NumberFilter;
interface NumberNullableFilter {
  equals?: number | null;
  not?: number | null | NumberNullableFilter;
  in?: number[];
  notIn?: number[];
  lt?: number;
  lte?: number;
  gt?: number;
  gte?: number;
}
type NumberNullableWhere = number | null | NumberNullableFilter;

interface BooleanFilter {
  equals?: boolean;
  not?: boolean | BooleanFilter;
}
type BooleanWhere = boolean | BooleanFilter;
type BooleanNullableWhere = boolean | null | BooleanFilter;

type DateTimeWhere = StringWhere;
type DateTimeNullableWhere = StringNullableWhere;
type BytesWhere = Uint8Array | { equals?: Uint8Array; not?: Uint8Array };
type JsonWhere = unknown;
`);

function scalarToWhereType(jsType: string, optional: boolean): string {
  switch (jsType) {
    case 'string':
      return optional ? 'StringNullableWhere' : 'StringWhere';
    case 'number':
      return optional ? 'NumberNullableWhere' : 'NumberWhere';
    case 'boolean':
      return optional ? 'BooleanNullableWhere' : 'BooleanWhere';
    case 'bigint':
      return optional ? 'NumberNullableWhere' : 'NumberWhere';
    case 'Uint8Array':
      return 'BytesWhere';
    default:
      return 'unknown';
  }
}

// Where types — per model
for (const model of models) {
  lines.push(`interface ${model.name}Where {`);
  lines.push(`  AND?: ${model.name}Where | ${model.name}Where[];`);
  lines.push(`  OR?: ${model.name}Where[];`);
  lines.push(`  NOT?: ${model.name}Where | ${model.name}Where[];`);
  for (const f of model.scalars) {
    lines.push(`  ${f.name}?: ${scalarToWhereType(f.type, f.optional)};`);
  }
  for (const r of model.relations) {
    if (r.list) {
      lines.push(
        `  ${r.name}?: { some?: ${r.target}Where; every?: ${r.target}Where; none?: ${r.target}Where };`,
      );
    } else {
      const nullable = r.optional ? ' | null' : '';
      lines.push(
        `  ${r.name}?: ${r.target}Where | { is?: ${r.target}Where${nullable}; isNot?: ${r.target}Where${nullable} };`,
      );
    }
  }
  lines.push('}');
  lines.push('');
}

// OrderBy types — per model
for (const model of models) {
  lines.push(`interface ${model.name}OrderBy {`);
  for (const f of model.scalars) {
    lines.push(`  ${f.name}?: OrderByField;`);
  }
  for (const r of model.relations) {
    if (!r.list) {
      lines.push(`  ${r.name}?: ${r.target}OrderBy;`);
    } else {
      lines.push(`  ${r.name}?: { _count?: OrderByField };`);
    }
  }
  lines.push('}');
  lines.push('');
}

// Create inputs
for (const model of models) {
  lines.push(`interface ${model.name}CreateInput {`);
  for (const f of model.scalars) {
    if (model.fkFields.has(f.name)) {
      // FK scalar — let nested relation supply it
      const type = f.optional ? `${f.type} | null` : f.type;
      lines.push(`  ${f.name}?: ${type};`);
      continue;
    }
    const opt = f.optional || f.hasDefault || MANAGED_OPTIONAL.has(f.name);
    const type = f.optional ? `${f.type} | null` : f.type;
    lines.push(`  ${f.name}${opt ? '?' : ''}: ${type};`);
  }
  for (const r of model.relations) {
    lines.push(
      `  ${r.name}?: Nested<${r.target}CreateInput, ${r.target}UpdateInput>;`,
    );
  }
  lines.push('}');
  lines.push('');
}

// Update inputs — all optional, scalars + nested writes
for (const model of models) {
  lines.push(`interface ${model.name}UpdateInput {`);
  for (const f of model.scalars) {
    const type = f.optional ? `${f.type} | null` : f.type;
    lines.push(`  ${f.name}?: ${type};`);
  }
  for (const r of model.relations) {
    lines.push(
      `  ${r.name}?: Nested<${r.target}CreateInput, ${r.target}UpdateInput>;`,
    );
  }
  lines.push('}');
  lines.push('');
}

// Argument shapes — generic on per-model Where/Select/Include/OrderBy types.
lines.push(`type OrderByField = 'asc' | 'desc';

interface FindManyArgs<W, I, S, O> {
  where?: W;
  orderBy?: O | O[];
  take?: number;
  skip?: number;
  include?: I;
  select?: S;
}

interface FindUniqueArgs<W, I, S> {
  where: W;
  include?: I;
  select?: S;
}

interface CreateArgs<D, I, S> {
  data: D;
  include?: I;
  select?: S;
}

interface UpdateArgs<W, D, I, S> {
  where: W;
  data: D;
  include?: I;
  select?: S;
}

interface DeleteArgs<W, I, S> {
  where: W;
  include?: I;
  select?: S;
}

interface Delegate<T, W, C, U, I, S, O> {
  findMany(args?: FindManyArgs<W, I, S, O>): Promise<T[]>;
  findFirst(args?: FindManyArgs<W, I, S, O>): Promise<T | null>;
  findFirstOrThrow(args?: FindManyArgs<W, I, S, O>): Promise<T>;
  findUnique(args: FindUniqueArgs<W, I, S>): Promise<T | null>;
  findUniqueOrThrow(args: FindUniqueArgs<W, I, S>): Promise<T>;
  create(args: CreateArgs<C, I, S>): Promise<T>;
  createMany(args: { data: C[] }): Promise<{ count: number }>;
  createManyAndReturn(args: { data: C[] }): Promise<T[]>;
  update(args: UpdateArgs<W, U, I, S>): Promise<T>;
  updateMany(args: { where?: W; data: U }): Promise<{ count: number }>;
  upsert(args: {
    where: W;
    create: C;
    update: U;
    include?: I;
    select?: S;
  }): Promise<T>;
  delete(args: DeleteArgs<W, I, S>): Promise<T>;
  deleteMany(args?: { where?: W }): Promise<{ count: number }>;
  count(args?: { where?: W }): Promise<number>;
  aggregate(args?: {
    where?: W;
    _count?: boolean;
    _min?: Record<string, boolean>;
    _max?: Record<string, boolean>;
  }): Promise<Record<string, unknown>>;
  groupBy(args: {
    by: string[];
    where?: W;
    _count?: boolean;
  }): Promise<Record<string, unknown>[]>;
}
`);

// DB interface
lines.push('interface DB {');
for (const model of models) {
  lines.push(
    `  ${camelCase(model.name)}: Delegate<${model.name}, ${model.name}Where, ${model.name}CreateInput, ${model.name}UpdateInput, ${model.name}Include, ${model.name}Select, ${model.name}OrderBy>;`,
  );
}
lines.push('  $transaction<T>(fn: (tx: DB) => Promise<T>): Promise<T>;');
lines.push(
  '  $executeRawUnsafe(sql: string, ...args: unknown[]): Promise<number>;',
);
lines.push(
  '  $queryRawUnsafe(sql: string, ...args: unknown[]): Promise<unknown>;',
);
lines.push('}');
lines.push('');

const output = lines.join('\n');
const outPath = resolve(import.meta.dirname, '../prisma/repl-types.d.ts');
writeFileSync(outPath, output, 'utf-8');
console.log(`Wrote ${models.length} model types to prisma/repl-types.d.ts`);
